language: "en-US"

reviews:
  profile: "assertive"
  request_changes_workflow: true
  review_status: true

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - "develop"

chat:
  auto_reply: true
